### ISSUE TITLE
Need to add a testing environment and...

### ISSUE THREAD

**Issue by Europia79** [BattlePlugins/BattlePluginsDev#1]
This is a really cool setup so far with tons of potential, however, these are several changes & additions that I'd like to put on the road map for the future.

https://github.com/BattlePlugins/BattlePluginsDev/blob/master/dependencies/runtime/binaries/pom.xml#L24
First, and most obvious, is that this is just flat out WRONG.
Running the `maven-install-plugin` with the goal `install-file` during the `install` phase is not wrong in a technical sense... It's just extremely weird & bizarre to install these dependencies every time you want to install updated BattlePlugins artifacts (like VirtualPlayers, BattleTracker, BattleArena, & arena extensions) into the local repo.  I kinda rush this out hastily because functionally, it works.

But really, we need to change the model where you clone the repo and run some kind of setup that only runs once (the first time) to setup a local BattlePlugins development environment.  At this point, I am not sure what the exact implementation of "setup" will be ?  There are a variety of ways we could handle this:  We could use maven archetypes.  We could use scripts.  Heck, we could probably even use gradle to handle our setup, & maven to handle our builds.  Yes, it's weird, but I have been looking for an excuse to play around with gradle.  Lemme know what you guys think about all these options.

In addition to "setup" handling the installation of dependencies into the local maven repo, we also want "setup" to build a local test environment under the `/server/` directory.  We need `.gitignore` to ignore this folder.  And we need the aggregator POMs to manage (with the `maven-antrun-plugin`) the installation of builds directly into the `/server/plugins` folder so that we can quickly test any changes.

So... for the local test environment (`/server/` folder), we need to give the user all the necessary server JARS (for convenience), and also give them a server startup script.

Ideally, we'd want to ship ONE script that is platform agnostic (works on any operating system: Windows, Linux, &/or Mac).  But worst case scenario, we ship with two scripts:  one for Windows & a second one for Linux/Mac.

But since this is a development environment that means the target audience is obviously developers.  So we might be able to get away with ONE Linux script that also works under Windows `msys` or `git-bash`.

Finally, I am very tempted to again "flatten" the directory structure more... Specifically, I want to "flatten" the `/dependencies` folder by removing the entire division of dependencies into the `/compile`, `/test`, & `/runtime` folders.  Also, I want to move BattleTracker to this POM with a `<module>../BattleTracker</module>` declaration.  And move VirtualPlayers to the top level directory with its invocation also under `/dependencies/pom.xml` (similar to BattleTracker).

Also, FYI that I have important local changes for VirtualPlayers that I need to finish & push.
So that's what will get done next.

Lemme know what you guys think about all this.
Did I miss anything ?

**Comment by Europia79** [comment]
There is also the issue of forking the arena plugin extensions into the `BattlePlugins` git repo.
Do we need to make another git repo (like `BP-Arenas` for example) where all the the Arena forks live ?

**Comment by RednedEpic** [comment]
I think Gradle will work out quite well for this project to be honest. From my experiences, it's a WHOLE lot faster than maven and considering that there is a lot of different modules and libraries, I feel like it's definitely the way to go. I do like the idea of the server too. I can't really say that I've seen it done with any other plugins before and I feel like that it will be a good solution for developers hoping to add on to BattleArena/BattleTracker or even an easy way for them to make their own extensions.

As for the BP-Arenas part, assuming you're talking about creating an entirely different GitHub organization, I don't think we need one unless we're looking at maintaining quite a few different extensions. For the time being, as we are only maintaining probably around 10 different ones, creating a whole new organization isn't ideal in my opinion. If we get to a point where we're maintaining a higher amount of extensions, then I think we should separate it.

**Comment by Europia79** [comment]
> If we get to a point where we're maintaining a higher amount of extensions, then I think we should separate it.
Well, there are over 30 extensions that I plan to work on (as you can see from the POM):
https://github.com/BattlePlugins/BattlePluginsDev/blob/master/arenas/pom.xml#L16-L49

> As for the BP-Arenas part
Yes, another Github organization.  The only reason why I suggest it is because of people complaining about all the forks on Discord.  So I thought that might be an appropriate solution and good for organizing our repos.  `BP-Arenas` is just an example name.  It could just as well be `BattlePlugins-Arenas` or `BattlePlugins-Extensions` or something else.

> I do like the idea of the server too. I can't really say that I've seen it done with any other plugins before and I feel like that it will be a good solution for developers hoping to add on to BattleArena/BattleTracker or even an easy way for them to make their own extensions.
Well, my initial use-case scenario for the test environment was in case my computer broke and I lost everything... I wouldn't have to waste time manually setting it all up again.  But you bring up an excellent point too:  That it'd be extremely helpful for developers to quickly jump into BattleArena development to create their own Arenas & have the newly created JARs automatically deployed to the test environment (`/server/plugins` folder).

> I think Gradle will work out quite well for this project to be honest.
lol.  No, i didn't mean use Gradle for the whole project.  What I was saying is that we could have a Gradle script that we use install the initial setup:  Install the binaries to the local maven repo & create the test environment.  But continue to use Maven for the builds.

Yeah, I can see how that'd be confusing for people to see a gradle script and think they could use that to build the project.  lol.

**Comment by Zach443** [comment]
> Yeah, I can see how that'd be confusing for people to see a gradle script and think they could use that to build the project. lol.

I definitely think that COULD be confusing, however anyone using this should probably be considered a "power user" aka perfectly able to figure it out as long as the script is only in this repo and clearly documented.

Using the gradle script doesn't seem to be an issue to me, as long as it works well I don't think anyone would mind. Especially when you factor in that IntelliJ has wonderful support for both Maven and Gradle built in. Not sure about NetBeans though 😉 

The test server directory seems like an excellent idea. It would really help people trying to contribute to any of the BattlePlugins as well as those trying to create their own extensions.

**Comment by Europia79** [comment]
https://gyazo.com/0d2abf215b468c39bb634f87737762be

shipping a test-server via maven-archetype is not gonna work because the maximum file size on github is 100 mb... And our bundled archive is almost 500 mb.
